spring:
  messages:
    basename: i18n/messages
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:postgresql://localhost/dorenisuru_development
  jpa:
    hibernate:
      ddl-auto: validate
  thymeleaf:
    mode: HTML

logging:
  level:
    jdbc: false
    jdbc.sqltiming: debug

app:
  effective-days-of-topics: 30
  bugsnag-api-key: b34e48f13375dc94b1deb4c5848a5ac7
  encrypt-key: xGXoJQmMR2
