spring:
  jpa:
    hibernate:
      ddl-auto: validate
  messages:
    basename: i18n/messages
  thymeleaf:
    mode: HTML

logging:
  level:
    jdbc: false
    jdbc.sqltiming: debug

app:
  bugsnag-api-key: b34e48f13375dc94b1deb4c5848a5ac7
